routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome')->middleware('guest');

Route::get('/access-denied', function () {
    return view('access-denied');
})->name('access-denied');

Auth::routes([
    'login' => true,
    'logout' => true,
    'register' => false,
    'reset' => false,
    'confirm' => false,
    'verify' => false,
]);

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
    Route::get('table-list', function () {
        return view('pages.table_list');
    })->name('table');

    Route::get('typography', function () {
        return view('pages.typography');
    })->name('typography');

    Route::get('icons', function () {
        return view('pages.icons');
    })->name('icons');

    Route::get('map', function () {
        return view('pages.map');
    })->name('map');

    Route::get('notifications', function () {
        return view('pages.notifications');
    })->name('notifications');

    Route::get('rtl-support', function () {
        return view('pages.language');
    })->name('language');

    Route::get('upgrade', function () {
        return view('pages.upgrade');
    })->name('upgrade');
});

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::any('/test', 'App\Http\Controllers\TestController@index');
});

Route::group(['prefix' => 'currency', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'currency.index', 'uses' => 'App\Http\Controllers\Books\CurrencyController@index']);
    Route::post('', ['as' => 'currency.store', 'uses' => 'App\Http\Controllers\Books\CurrencyController@store']);
    Route::get('/create', ['as' => 'currency.create', 'uses' => 'App\Http\Controllers\Books\CurrencyController@create']);
    Route::get('/{currency}/edit', ['as' => 'currency.edit', 'uses' => 'App\Http\Controllers\Books\CurrencyController@edit']);
    Route::post('/{currency}', ['as' => 'currency.destroy', 'uses' => 'App\Http\Controllers\Books\CurrencyController@destroy']);
});

Route::group(['prefix' => 'payment-system', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'payment-system.index', 'uses' => 'App\Http\Controllers\Books\PaymentSystemController@index']);
    Route::post('', ['as' => 'payment-system.store', 'uses' => 'App\Http\Controllers\Books\PaymentSystemController@store']);
    Route::get('/create', ['as' => 'payment-system.create', 'uses' => 'App\Http\Controllers\Books\PaymentSystemController@create']);
    Route::get('/{paymentSystem}/edit', ['as' => 'payment-system.edit', 'uses' => 'App\Http\Controllers\Books\PaymentSystemController@edit']);
    Route::post('/{paymentSystem}', ['as' => 'payment-system.destroy', 'uses' => 'App\Http\Controllers\Books\PaymentSystemController@destroy']);
});

Route::group(['prefix' => 'box', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'box.index', 'uses' => 'App\Http\Controllers\Books\BoxController@index']);
    Route::post('', ['as' => 'box.store', 'uses' => 'App\Http\Controllers\Books\BoxController@store']);
    Route::get('/create', ['as' => 'box.create', 'uses' => 'App\Http\Controllers\Books\BoxController@create']);
    Route::get('/{box}/edit', ['as' => 'box.edit', 'uses' => 'App\Http\Controllers\Books\BoxController@edit']);
    Route::post('/{box}', ['as' => 'box.destroy', 'uses' => 'App\Http\Controllers\Books\BoxController@destroy']);
});

Route::group(['prefix' => 'partners', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'partners.index', 'uses' => 'App\Http\Controllers\Books\PartnersController@index']);
    Route::post('', ['as' => 'partners.store', 'uses' => 'App\Http\Controllers\Books\PartnersController@store']);
    Route::get('/create', ['as' => 'partners.create', 'uses' => 'App\Http\Controllers\Books\PartnersController@create']);
    Route::get('/{partners}/edit', ['as' => 'partners.edit', 'uses' => 'App\Http\Controllers\Books\PartnersController@edit']);
    Route::post('/{partners}', ['as' => 'partners.destroy', 'uses' => 'App\Http\Controllers\Books\PartnersController@destroy']);
});

Route::group(['prefix' => 'dds', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'dds.index', 'uses' => 'App\Http\Controllers\Books\DDSController@index']);
    Route::post('', ['as' => 'dds.store', 'uses' => 'App\Http\Controllers\Books\DDSController@store']);
    Route::get('/create', ['as' => 'dds.create', 'uses' => 'App\Http\Controllers\Books\DDSController@create']);
    Route::get('/{dds}/edit', ['as' => 'dds.edit', 'uses' => 'App\Http\Controllers\Books\DDSController@edit']);
    Route::post('/{dds}', ['as' => 'dds.destroy', 'uses' => 'App\Http\Controllers\Books\DDSController@destroy']);
});

Route::group(['prefix' => 'top-destinations', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'top-destinations.index', 'uses' => 'App\Http\Controllers\Books\TopDestinationsController@index']);
    Route::post('', ['as' => 'top-destinations.store', 'uses' => 'App\Http\Controllers\Books\TopDestinationsController@store']);
    Route::get('/create', ['as' => 'top-destinations.create', 'uses' => 'App\Http\Controllers\Books\TopDestinationsController@create']);
    Route::get('/{topDestinations}/edit', ['as' => 'top-destinations.edit', 'uses' => 'App\Http\Controllers\Books\TopDestinationsController@edit']);
    Route::post('/{topDestinations}', ['as' => 'top-destinations.destroy', 'uses' => 'App\Http\Controllers\Books\TopDestinationsController@destroy']);
});

Route::group(['prefix' => 'top-destinations-group', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::get('', ['as' => 'top-destinations-group.index', 'uses' => 'App\Http\Controllers\Books\TopDestinationsGroupController@index']);
    Route::post('', ['as' => 'top-destinations-group.store', 'uses' => 'App\Http\Controllers\Books\TopDestinationsGroupController@store']);
    Route::get('/create', ['as' => 'top-destinations-group.create', 'uses' => 'App\Http\Controllers\Books\TopDestinationsGroupController@create']);
    Route::get('/{topDestinationsGroup}/edit', ['as' => 'top-destinations-group.edit', 'uses' => 'App\Http\Controllers\Books\TopDestinationsGroupController@edit']);
    Route::post('/{topDestinationsGroup}', ['as' => 'top-destinations-group.destroy', 'uses' => 'App\Http\Controllers\Books\TopDestinationsGroupController@destroy']);
});


Route::group(['prefix' => 'income-expense', 'middleware' => ['auth', 'role:admin/economist']], function () {
    Route::match(['GET', 'POST'], '', ['as' => 'income-expense.index', 'uses' => 'App\Http\Controllers\IncomeExpenseController@index']);
    Route::post('/list', ['as' => 'income-expense.list', 'uses' => 'App\Http\Controllers\IncomeExpenseController@getList']);
    Route::get('/reset-filter', ['as' => 'income-expense.reset-filter', 'uses' => 'App\Http\Controllers\IncomeExpenseController@resetFilter']);
    Route::post('/store', ['as' => 'income-expense.store', 'uses' => 'App\Http\Controllers\IncomeExpenseController@store']);
    Route::get('/create/{type}', ['as' => 'income-expense.create', 'uses' => 'App\Http\Controllers\IncomeExpenseController@create']);
    Route::get('/{incomeExpense}/edit', ['as' => 'income-expense.edit', 'uses' => 'App\Http\Controllers\IncomeExpenseController@edit']);
    Route::post('/{incomeExpense}', ['as' => 'income-expense.destroy', 'uses' => 'App\Http\Controllers\IncomeExpenseController@destroy']);
    Route::get('/export', ['as' => 'income-expense.export', 'uses' => 'App\Http\Controllers\IncomeExpenseController@export']);
    //Route::get('/export-test', ['as' => 'income-expense.export-test', 'uses' => 'App\Http\Controllers\IncomeExpenseController@exportTest']);
});

Route::group(['prefix' => 'bid', 'middleware' => ['auth', 'role:admin/economist/manager']], function () {
    Route::match(['GET', 'POST'], '', ['as' => 'bid.index', 'uses' => 'App\Http\Controllers\BidController@index']);
    Route::post('/list', ['as' => 'bid.list', 'uses' => 'App\Http\Controllers\BidController@getBidList']);
    Route::post('/add-offer', ['as' => 'bid.add-offer', 'uses' => 'App\Http\Controllers\BidController@addOffer']);
    Route::get('/reset-filter', ['as' => 'bid.reset-filter', 'uses' => 'App\Http\Controllers\BidController@resetFilter']);
    Route::post('/store', ['as' => 'bid.store', 'uses' => 'App\Http\Controllers\BidController@store']);
    Route::get('/create', ['as' => 'bid.create', 'uses' => 'App\Http\Controllers\BidController@create']);

app/Models/BaseModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class BaseModel extends Model
{
    use HasFactory;

    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->created_user_id = Auth()->user()->id;
        });

        static::updating(function ($model) {
            $model->updated_user_id = Auth()->user()->id;
        });
    }

    public function createdUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_user_id', 'id')
            ->withDefault();
    }

    public function updatedUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_user_id', 'id')
            ->withDefault();
    }

    public function deletedUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'deleted_user_id', 'id')
            ->withDefault();
    }

    /**
     * Фамилия И.О.
     *
     * @param string $relationUser
     *  Отношение к таблице пользователей.
     * @return string
     */
    private function getFullName( string $relationUser ): string
    {
        $fullName = '-';
        if ( ! is_null( $this->$relationUser ) ) {
            $fullName = $this->$relationUser->surname . ' ' .
                mb_substr($this->$relationUser->name, 0, 1) . '.' .
                mb_substr($this->$relationUser->patronymic, 0, 1) . '.';
        }
        return $fullName;
    }

    /**
     * ФИО пользователя который создал запись.
     *
     * @return string
     */
    public function getCreatedFullNameAttribute(): string
    {
        return $this->getFullName( 'createdUser' );
    }

    /**
     * ФИО пользователя который редактировал запись.
     *
     * @return string
     */
    public function getUpdatedFullNameAttribute(): string
    {
        return $this->getFullName( 'createdUser' );
    }

    /**
     * ФИО пользователя который удалил запись.
     *
     * @return string
     */
    public function getDeletedFullNameAttribute(): string
    {
        return $this->getFullName( 'deletedUser' );
    }
}

app/Models/Books/Box.php
<?php

namespace App\Models\Books;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Config;
use App\Models\BaseModel;

class Box extends BaseModel
{
    protected $table = 'box';

    protected $fillable = [
        'type_box',
        'unique_name',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_user_id',
        'updated_user_id',
        'deleted_user_id',
        'direction_id',
    ];

    public function direction(): belongsTo
    {
        return $this->belongsTo(Direction::class, 'direction_id', 'id')->withDefault();
    }

    public function getDirectionDescrAttribute(): string
    {
        return $this->direction->paymentSystem->descr . ' ' . $this->direction->currency->descr;
    }

    public function getTypeBoxDescrRuAttribute()
    {
        return ($this->type_box == 'card')
            ? Config::get('constants.type_box_ru.card')
            : Config::get('constants.type_box_ru.wallet');
    }

    public function getFormatName()
    {
        return $this->getDirectionDescrAttribute() . ': ' . $this->unique_name;
    }

    public function getBoxDataFromDirectionId($id)
    {
        $boxes = $this->where('direction_id', '=', $id)->get();
        $options = array();
        foreach ($boxes as $val) {
            $options[] = [$val->id, $val->getFormatName(),];
        }
        return $options;
    }
}

app/Models/Books/Client.php
<?php

namespace App\Models\Books;

use App\Models\BaseModel;

class Client extends BaseModel
{
    protected $table = 'clients';

    protected $fillable = [
        'fullname',
        'email',
        'phone',
        'note',
        'created_user_id',
        'updated_user_id',
        'deleted_user_id',
    ];

    /**
     * Полная информация о клиенте.
     *
     * @return string
     */
    public function getFullInfoAttribute(): string
    {
        return $this->fullname .
            ( ! is_null($this->email ) ? ' / ' . $this->email : '' ) .
            ( ! is_null($this->phone ) ? ' / ' . $this->phone  : '' );
    }
}

app/Models/Books/Currency.php
<?php

namespace App\Models\Books;

use App\Models\BaseModel;
use App\Models\User;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Currency extends BaseModel
{
    protected $table = 'currency';

    protected $fillable = [
        'descr',
        'balance',
        'rate',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_user_id',
        'updated_user_id',
        'deleted_user_id',
    ];

//    protected $casts = [
//        'descr' => 'string:16',
//        'balance' => 'decimal:18:8',
//        'rate' => 'decimal:18:8',
//        'created_at' => 'datetime',
//        'updated_at' => 'datetime',
//        'deleted_at' => 'datetime',
//        'created_user_id' => 'integer',
//        'updated_user_id' => 'integer',
//        'deleted_user_id' => 'integer',
//    ];


    /**
     * Баланс в рубле.
     *
     * @return float|int
     */
    public function getBalanceRubleAttribute()
    {
        return $this->balance * $this->rate;
    }
}

app/Models/Books/Partners.php
<?php

namespace App\Models\Books;

use App\Models\BaseModel;

class Partners extends BaseModel
{
    protected $table = 'partners';

    protected $fillable = [
        'id',
        'descr',
    ];
}

app/Http/Controllers/Books/BoxController.php
<?php

namespace App\Http\Controllers\Books;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreBox;

use App\Models\Books\Box;
use App\Models\Books\Direction;
use Exception;
use Illuminate\Contracts\View\View;

use App\Traits\ExceptionSQL;

class BoxController extends Controller
{
    use ExceptionSQL;

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $listBox = Box::all();
        return view('books.box.index', compact('listBox'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $listDirection = (new Direction)->sorted();

        return view('books.box.show', compact('listDirection',));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreBox $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreBox $request): \Illuminate\Http\RedirectResponse
    {
        try {
            Box::on()->updateOrCreate(['id' => $request->id], [
                'type_box' => $request->type_box,
                'unique_name' => $request->unique_name,
                'direction_id' => $request->direction_id,
            ]);

            return redirect()->route('box.index');

        } catch ( Exception $e ) {
            return back()
                ->withInput()
                ->withErrors( $this->getMessageFilterSQLError( $e ) );
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Box $box
     * @return View
     */
    public function edit(Box $box): View
    {
        $listDirection = (new Direction)->sorted();

        return view('books.box.show', compact('box', 'listDirection',));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Box $box
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Box $box)
    {
        try {
            $box->delete();
        } catch ( Exception $e ) {
            return back()
                ->withInput()
                ->withErrors( $this->getMessageFilterSQLError( $e ) );
        }
        return redirect()->route('box.index');
    }
}

resources/views/books/box/index.blade.php
@extends('layouts.app', ['activePage' => 'box', 'titlePage' => 'Счета'])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-success">
                            <h4 class="card-title ">Счета</h4>
                            <div class="card-actions ml-auto mr-auto">
                                <a href="{{route('box.create')}}"
                                   class="btn btn-primary"
                                   role="button">Добавить</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                        <th>Открыть</th>
                                        <th>ID</th>
                                        <th>Тип</th>
                                        <th>Уникальное имя</th>
                                        <th>Направление</th>
                                        <th>Дата создания</th>
                                        <th>Дата изменения</th>
                                        <th>Кто добавил</th>
                                        <th>Кто изменил</th>
                                        <th>Удалить</th>
                                    </thead>
                                    <tbody>
                                        @isset( $listBox )
                                            @foreach($listBox as $box)
                                                <tr>
                                                    <td>
                                                        <a href="{{ route('box.edit', ['box' => $box->id]) }}" type="button"
                                                           rel="tooltip" title="Редактировать"
                                                           class="btn btn-primary btn-link btn-sm">
                                                            <i class="material-icons">edit</i>
                                                        </a>
                                                    </td>
                                                    <td>{{$box->id}}</td>
                                                    <td>{{$box->type_box_descr_ru}}</td>
                                                    <td>{{$box->unique_name}}</td>
                                                    <td>{{$box->direction_descr}}</td>
                                                    <td>{{$box->created_at}}</td>
                                                    <td>{{$box->updated_at}}</td>
                                                    <td>{{$box->created_full_name}}</td>
                                                    <td>{{$box->updated_full_name}}</td>
                                                    <td>
                                                        <button
                                                            type="button"
                                                            class="btn btn-danger btn-link btn-sm delete-confirm"
                                                            rel="tooltip"
                                                            data-id="{{$box->id}}"
                                                            data-toggle="modal"
                                                            data-target="#deleteModal">
                                                            <i class="material-icons">close</i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @endisset
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.modal.delete-confirm', ['baseUrlDelete' => 'box'])
    </div>
@endsection

resources/views/books/box/show.blade.php
@extends('layouts.app', ['activePage' => 'box', 'titlePage' => 'Счета: Добавление/Редактирование'])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('box.store') }}" autocomplete="off" id="form-box"
                          class="form-horizontal">
                        @csrf
                        <div class="card">
                            <div class="card-header card-header-success">
                                <h4 class="card-title">Счет</h4>
                                <p class="card-category">Добавление/Редактирование</p>
                            </div>

                            <div class="card-body">
                                @if(isset($box))
                                    <div class="row">
                                        <label class="col-sm-2 col-form-label">ID</label>
                                        <div class="col-sm-7">
                                            <div class="form-group">
                                                <input class="form-control" name="id" id="input-id"
                                                       type="text" readonly value="{{ $box->id ?? '' }}"/>
                                            </div>
                                        </div>
                                    </div>
                                @endif

                                <div class="row">
                                    <label class="col-sm-2 col-form-label" for="input-type_box">Тип счета*</label>
                                    <div class="col-sm-10">
                                        <div class="form-group{{ $errors->has('type_box') ? ' has-danger' : '' }}">
                                            <input name="type_box" id="input-type_box-card" type="radio"
                                                   value="{{config('constants.type_box.card')}}" required="true"
                                                   {{ ( (old('type_box') === 'card') || (!empty ($box->type_box) && $box->type_box == 'card') ) ? 'checked' : '' }}
                                                   aria-required="true"/>
                                            <label for="input-type_box-card" class="col-sm-1 radio-inline">
                                                {{config('constants.type_box_ru.card')}}
                                            </label>
                                            <input name="type_box" id="input-type_box-wallet" type="radio"
                                                   value="{{config('constants.type_box.wallet')}}" required="true"
                                                   {{ ( (old('type_box') === 'wallet') || (!empty ($box->type_box) && $box->type_box == 'wallet') ) ? 'checked' : '' }}
                                                   aria-required="true"/>
                                            <label for="input-type_box-wallet" class="col-sm-1 radio-inline">
                                                {{config('constants.type_box_ru.wallet')}}
                                            </label>
                                            @if ($errors->has('type_box'))
                                                <span id="name-error" class="error text-danger" for="input-type_box">
                                                    {{ $errors->first('type_box') }}
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label" for="input-unique_name">Уникальный
                                        номер*</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('unique_name') ? ' has-danger' : '' }}">
                                            <input
                                                class="form-control{{ $errors->has('unique_name') ? ' is-invalid' : '' }}"
                                                name="unique_name"
                                                id="input-unique_name"
                                                type="text"
                                                placeholder="Наименование"
                                                value="{{ $box->unique_name ?? '' }}"
                                                required="true"
                                                aria-required="true"/>
                                            @if ($errors->has('unique_name'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-unique_name">{{ $errors->first('unique_name') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-group form-group required">
                                        <label class="col-sm-2 col-form-label input-group-addon"
                                               for="select-direction_id">
                                            Направление*
                                        </label>
                                        <div class="col-sm-2">
                                            <select id="select-direction_id" name="direction_id"
                                                    class="selectpicker" data-style="btn btn-primary btn-round">
                                                <option disabled selected>Выберите из списка</option>
                                                @isset($listDirection)
                                                    @foreach($listDirection as $direction)
                                                        <option value="{{$direction->id}}"
                                                                @if(isset($box) && $box->direction_id === $direction->id )
                                                                selected
                                                            @endif>
                                                            {{$direction->paymentSystem->descr}} {{$direction->currency->descr}}
                                                        </option>
                                                    @endforeach
                                                @endisset
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                @if(isset($box))
                                    <div class="row">
                                        <label class="col-sm-2 col-form-label">Дата создания</label>
                                        <div class="col-sm-7">
                                            <div class="form-group">
                                                <input class="form-control" name="created_at"
                                                       id="input-created_at" type="text" disabled
                                                       value="{{ $box->created_at ?? '' }}"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label class="col-sm-2 col-form-label">Дата редактирования</label>
                                        <div class="col-sm-7">
                                            <div class="form-group">
                                                <input class="form-control" name="updated_at"
                                                       id="input-updated_at" type="text" disabled
                                                       value="{{ $box->updated_at ?? '' }}"/>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            </div>

                            <div class="card-footer ml-auto mr-auto">
                                <div class="col-lg-6 text-left">
                                    <button type="submit" form="form-box" class="btn btn-primary">Сохранить</button>
                                </div>
                                <div class="col-lg-6 text-right">
                                    <a href="{{ route('box.index') }}" class="btn btn-block" role="button">Назад</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection